### ISSUE TITLE
X86_32 missing valid Windows pattern for os.arch

### ISSUE THREAD

**Issue by phrack** [PatternConsulting/opencv#11]
New versions of Oracle's 32-bit JRE for Windows often have os.arch set to x86 (x86_64 being the 64-bit version). It appears "x86" needs to be added to the list of patterns in this line: https://github.com/PatternConsulting/opencv/blob/58d13dfb7f724c041dcf8af4f62ed2a8c2da6fd1/src/main/java/nu/pattern/OpenCV.java#L65. This is causing an UnsupportedOperationException to be thrown even in cases where the OS and architecture actually are supported, e.g. on both 32-bit and 64-bit Windows with 32-bit Oracle JRE:

Caused by: java.lang.UnsupportedOperationException: Architecture "x86" is not supported. at nu.pattern.OpenCV$Arch.getCurrent(OpenCV.java:88) at nu.pattern.OpenCV.extractNativeBinary(OpenCV.java:291) at nu.pattern.OpenCV.access$100(OpenCV.java:22) at nu.pattern.OpenCV$SharedLoader.<init>(OpenCV.java:178) at nu.pattern.OpenCV$SharedLoader.<init>(OpenCV.java:162) at nu.pattern.OpenCV$SharedLoader$Holder.<clinit>(OpenCV.java:202) ...

**Comment by phrack** [comment]
PS. Here is how we fetch the dependency, which I suppose is a fork of this project to add Windows support: compile 'org.openpnp:opencv:2.4.11-1.

**Comment by michaelahlers** [comment]
@vonnieda addressed this in his fork. Recommend users migrate to [his package](https://github.com/openpnp/opencv).
